import { FC } from 'react';
import style from './Layout.module.scss';

import { Header, Footer } from '../components';
import Head from 'next/head';

export const Layout: FC<ILayout> = ({
  header = <Header />,
  children,
  footer = <Footer />,
  isHeader = true,
  isFooter = true,
  title,
}) => {
  return (
    <div className={style.layout}>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {isHeader && header}
      <div className={style.children}>{children}</div>
      {isFooter && footer}
    </div>
  );
};
